import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import JSZip from 'jszip';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ configName: string }> }
) {
  try {
    const { configName } = await params;
    
    const config = await prisma.appConfiguration.findUnique({
      where: { name: configName },
    });

    if (!config) {
      return NextResponse.json({ error: 'Config not found' }, { status: 404 });
    }

    const schema: any = config.schema;
    const zip = new JSZip();

    // 1. Generate specific Prisma Schema based on the JSON
    let prismaModels = `generator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;
    
    for (const entity of schema.entities) {
      prismaModels += `model ${entity.name} {\n  id String @id @default(uuid())\n`;
      for (const field of entity.fields) {
        let type = 'String';
        if (field.type === 'number') type = 'Int';
        if (field.type === 'boolean') type = 'Boolean';
        if (field.type === 'date') type = 'DateTime';
        if (!field.required) type += '?';
        prismaModels += `  ${field.name} ${type}\n`;
      }
      prismaModels += `  createdAt DateTime @default(now())\n}\n\n`;
    }

    zip.file('prisma/schema.prisma', prismaModels);

    // 2. Generate Next.js API Routes for their entities
    for (const entity of schema.entities) {
      const apiCode = `import { NextResponse } from 'next/server';\nimport prisma from '@/lib/prisma';\n\nexport async function GET() {\n  const data = await prisma.${entity.name.toLowerCase()}.findMany();\n  return NextResponse.json(data);\n}\n\nexport async function POST(req: Request) {\n  const body = await req.json();\n  const data = await prisma.${entity.name.toLowerCase()}.create({ data: body });\n  return NextResponse.json(data);\n}\n`;
      zip.file(`app/api/${entity.name.toLowerCase()}/route.ts`, apiCode);
    }

    // 3. Generate README
    const readme = `# ${schema.name} Source Code\n\nThis codebase was dynamically generated by the AI App Builder.\n\n## Instructions\n1. Run \`npm install\`\n2. Add your \`DATABASE_URL\` to \`.env\`\n3. Run \`npx prisma db push\`\n4. Start the server with \`npm run dev\``;
    zip.file('README.md', readme);
    
    // 4. Attach original config
    zip.file('ai-config.json', JSON.stringify(schema, null, 2));

    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' });

    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${configName}-source.zip"`,
      },
    });

  } catch (error) {
    console.error('Export Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
